[[redirects]]
  from = "/api/*"
  to = "http://34.201.108.53:8080/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
    [headers.values]
      Access-Control-Allow-Origin = "http://localhost:5173"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"
      Access-Control-Allow-Credentials = "true"